INSERT INTO CRYPTOCURRENCY (CURRENCY_ID, ASK_PRICE, BID_PRICE, NAME) VALUES ('BTCUSDT',0,0, 'BTC/USDT'),('ETHUSDT', 0,0, 'EHT/USDT'),('USDT',1, 1,'Tether')
INSERT INTO WALLET(WALLET_ID, TRANSACTION_ID, ADDRRESS) VALUES ('walb1w1', NULL, '23xb11321f3'), ('walb2w2', NULL, '51xXb1321f7')
INSERT INTO BALANCE (BALANCE_ID, TOKEN_VALUE, TOKEN_AMOUNT, CURRENCY_ID, WALLET_ID) VALUES ('b1', 50000, 50000, 'USDT', 'walb1w1')
INSERT INTO CUSTOMER (CUSTOMER_ID, WALLET_ID, NAME, EMAIL) VALUES ('C1W1', 'walb1w1', 'Clarice', 'clarice@email.com')



